### ISSUE TITLE
Draw cached layer in background while extruding

### ISSUE THREAD

**Issue by danielgamage** [danielgamage/Extrude-Tool#12]
should function as the standard select tool when dragging, where just the outlines are drawn as shown here:

![screen shot 2016-09-22 at 3 48 53 am](https://cloud.githubusercontent.com/assets/1642599/18740438/b121882e-8077-11e6-8b66-65eccf799cb6.png)

**Comment by danielgamage** [comment]
I understand how to generally _draw_ an `NSBezierPath` path from cache, but I'm at a total loss about how that path is positioned / scaled.

``` Objc
- (void)drawBackground {
   if (bgPath) {
       [[NSColor lightGrayColor] set];
       [bgPath setLineWidth: 1];
       [bgPath stroke];
   }
}
```

![screen shot 2016-09-22 at 6 59 47 am](https://cloud.githubusercontent.com/assets/1642599/18745909/40fb6a04-8092-11e6-9c44-f82420e4011a.png)

The result ends up above the canvas and usually also scaled to counter effect the UI scale. The `x` and `y` values on the `[layer bounds]` and `[bgPath bounds]` are the same, making this make less sense to me...

@schriftgestalt What other variables affect the positioning of an `NSBezierPath` when it's drawn on the view? Can I ask how this is implemented in the Select tool?

**Comment by schriftgestalt** [comment]
I would use

```
- (void)drawBackgroundForLayer:(GSLayer*)Layer atPoint:(NSPoint)aPoint asActive:(BOOL)Active;
```

The you need to transform the path like this:

```
NSView <GSGlyphEditViewProtocol> *EditView = _editViewController.graphicView;
CGFloat Scale = [EditView scale];
NSAffineTransform *Transformer = [[NSAffineTransform alloc] init];
[Transformer translateXBy:aPoint.x yBy:aPoint.y];
[Transformer scaleBy:Scale];
[bgPath transformUsingAffineTransform:Transformer];
[bgPath stroke];
```

**Comment by schriftgestalt** [comment]
Or you do this in mouseDown or before you add the extra nodes.

```
_editViewController.shadowLayer = [_editViewController.graphicView.activeLayer copy];
```
