### ISSUE TITLE
Mouse pointers from other tools are shown sometimes.

### ISSUE THREAD

**Issue by dyyybek** [danielgamage/Extrude-Tool#13]
## Bug Report

Minor bug if any.
### What is happening?

Mouse pointers from other tools are shown sometimes.
### What steps can one take to reproduce this issue?
1. Select nodes with "V" selection tool.
2. Pick another tool for example "P" pen tool.
3. Then pick the extrude tool.
### Which version of Glyphs does this occur in?

This issue occurs on `Glyphs v2.4b (923)`.
### Which version of MacOS are you on?

I'm on `MacOS 10.11.5`.

**Comment by danielgamage** [comment]
Thanks for reporting @dyyybek. I updated the plugin, but let me know if this issue persists for you.
