### ISSUE TITLE
Support extrusion of bezier paths

### ISSUE THREAD

**Issue by danielgamage** [danielgamage/Extrude-Tool#3]
The current behavior is very messy:

![screen shot 2016-09-20 at 4 19 36 am](https://cloud.githubusercontent.com/assets/1642599/18662715/891dc908-7ee9-11e6-8cbf-da0bff073a73.jpg)

The desired behavior is to have sharp corners where the selection begins and ends (at the base and ends of the extrusion) but maintain the curvature of the extruded path:

![screen shot 2016-09-20 at 4 18 56 am](https://cloud.githubusercontent.com/assets/1642599/18662725/8f7c9fe0-7ee9-11e6-9603-de58ef05dc5e.jpg)

**Comment by danielgamage** [comment]
I thought this was just because the node connections weren't `SHARP` after extruding but it doesn't seem to help much. If you make a circle and select, say, the top and right nodes & the `OFFCURVE`s between them, then use the extrude tool, the nodes are all in the correct order but the path being drawn just isn't correct. Any ideas @schriftgestalt ?

![screen shot 2016-09-20 at 5 18 15 am](https://cloud.githubusercontent.com/assets/1642599/18664679/b203cfd6-7ef1-11e6-961f-6273acb7276c.jpg)

![screen shot 2016-09-20 at 5 18 22 am](https://cloud.githubusercontent.com/assets/1642599/18664682/b641a5aa-7ef1-11e6-8172-3d54003db32a.jpg)

**Comment by schriftgestalt** [comment]
The tool is responsible to leave the path in a constant state. Please make sure, that there are always two off curve and on curve node. Not more or less off curve nodes before a curve node. You have clearly more off curve nodes in a row. Or, if you just copy a node, you might need to adjust the node type to LINE.

**Comment by danielgamage** [comment]
@schriftgestalt Ohhh. That `LINE` conversion works perfectly when applied to the 2nd of the two edge nodes. Thanks for the explanation!
